### ISSUE TITLE
Problem with colors when are rgb tuples

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/fda#72]
The following example crashed due to the use of numpy array to store the colors added in #66
https://github.com/GAA-UAM/fda/blob/940caa755e40cf26395e22a772806cba3ff18fd7/examples/plot_pairwise_alignment.py#L126-L133

**Comment by vnmabus** [comment]
Can you provide the exception trace?

**Comment by pablomm** [comment]
The problem when the color is a rgb tuple [r, g, b, a], is that np.asarray([r,g,b,a]).repeat(nsamples) creates an array with [r,g,b,a,r,g,b,a, ... ] instead of [[r,g,b,a],[r,g,b,a], ...] and only the r color is passed.

> Traceback (most recent call last):
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py", line 166, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (0.8243137254901961, None)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 83, in _draw
    self.figure.draw(renderer)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/lines.py", line 761, in draw
    ln_color_rgba = self._get_rgba_ln_color()
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/lines.py", line 1262, in _get_rgba_ln_color
    return mcolors.to_rgba(self._color, self._alpha)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py", line 168, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py", line 219, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 0.8243137254901961
Traceback (most recent call last):
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/matplotlib/colors.py", line 166, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (0.8243137254901961, None)
